flaskr/mains/routes.py
from flask import Blueprint, render_template, url_for
from flask.helpers import flash
from flask_login import current_user
from flaskr import app
from flaskr.mains.form import SearchForm
from flaskr.models import Event, Profile
from flaskr.utils import is_eligable
from sqlalchemy import func
from werkzeug.utils import redirect

mains = Blueprint("mains", __name__)


@mains.route("/homepage")
@mains.route("/")
def homepage():
    eligable = is_eligable(current_user)
    events = Event.query.order_by(Event.event_time)[:12]
    return render_template("mains/homepage.html", eligable=eligable, events=events, len=len)

@app.context_processor
def base():
    form = SearchForm()
    return dict(s_form=form)

@mains.route("/search", methods=["GET", "POST"])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        searched = form.search.data
        events_by_title = Event.query.filter(func.lower(Event.title).like("%" + searched.lower() + "%"))
        events_by_location = Event.query.filter(func.lower(Event.place_name).like("%" + searched.lower() + "%"))
        
        event_set = set()
        for event in events_by_title:
            event_set.add(event)
        for event in events_by_location:
            event_set.add(event)
        
        profiles_by_first = Profile.query.filter(func.lower(Profile.first_name).like("%" + searched.lower() + "%"))
        profiles_by_last = Profile.query.filter(func.lower(Profile.last_name).like("%" + searched.lower() + "%"))
        
        profile_set = set()
        for profile in profiles_by_first:
            profile_set.add(profile)
        for profile in profiles_by_last:
            profile_set.add(profile)
        
        return render_template("mains/search.html", s_form=form, searched=searched, events=event_set, profiles=profile_set, len=len)
    flash("No search input given.", "danger")
    return redirect(url_for("mains.homepage"))
    

flaskr/users/routes.py
import os

from flask import (Blueprint, flash, redirect, render_template, request,
                   session, url_for)
from flask_login import current_user, login_required
from flask_login import login_user as login_user_function
from flask_login import logout_user as logout_user_function
from flaskr import app, bcrypt, db
from flaskr.decorators import is_admin, is_unbanned, is_verified
from flaskr.mails import send_mail
from flaskr.models import (Complain, ComplainCategory, Event, Notification,
                           Profile, Role, User)
from flaskr.notifications.utils import NotificationMessage
from flaskr.users.forms import *
from flaskr.users.utils import generate_token, password_reset_key_mail_body
from jwt import encode

users = Blueprint("users", __name__, url_prefix="/users")


@users.route("/")
@login_required
@is_admin
def get_users():
    all_users = User.query.all()
    return render_template("users/view_all_user.html", users=all_users)


@users.route("/register", methods=["GET", "POST"])
def register_user():
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    form = RegisterForm()
    if form.validate_on_submit():
        # Generating token
        generated_token_for_email = generate_token(6)
        # Hashing
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        hashed_token = bcrypt.generate_password_hash(
            generated_token_for_email).decode("utf-8")
        # Creating user
        all_users = User.query.all()
        user = None
        if len(all_users) == 0:
            user = User(form.email.data, hashed_password,
                        hashed_token, Role.ADMIN)
        else:
            user = User(form.email.data, hashed_password,
                        hashed_token, Role.GENERAL)
        db.session.add(user)
        db.session.commit()
        # Creating profile
        profile = Profile(form.first_name.data, form.last_name.data,
                          form.dob.data, form.gender.data, user.id)
        db.session.add(profile)
        db.session.commit()
        # Sending email
        send_mail(user.email, "Email Verification Code",
                  f"Your Token is {generated_token_for_email}")
        fetched_user = User.query.filter_by(id=user.id).first()
        flash(
            f"Account created for {fetched_user.profile.first_name} {fetched_user.profile.last_name}", "success")
        return redirect(url_for("users.login_user"))
    return render_template("users/register.html", form=form, active='register')


@users.route("/login", methods=["GET", "POST"])
def login_user():
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    form = LoginForm()
    if form.validate_on_submit():
        # Fetching the user
        fetched_user = User.query.filter_by(email=form.email.data).first()
        # Checking the email and password
        if fetched_user and bcrypt.check_password_hash(fetched_user.password, form.password.data):
            login_user_function(fetched_user, remember=form.remember_me.data)
            next_page = request.args.get("next")
            response = redirect(next_page) if next_page else redirect(
                url_for('mains.homepage'))
            # jtw
            jwt_token = encode({
                "id": fetched_user.id,
                "email": fetched_user.email,
            }, app.config.get("JWT_SECRET_KEY"), algorithm="HS256")
            response.set_cookie("access_token", jwt_token, max_age=60*60*30)
            flash("Login Successfull.", "success")
            return response
        else:
            flash("Login Failed! Please Check Email and Password.", "danger")
    return render_template("users/login.html", form=form, active='login')


@users.route("/logout")
@login_required
def logout_user():
    logout_user_function()
    return redirect(url_for("users.login_user"))


@users.route("/forget_password", methods=["GET", "POST"])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        # Fetching the user
        user = User.query.filter_by(email=form.email.data).first()
        # Sending email
        send_mail(user.email, "Password Reset Token",
                  password_reset_key_mail_body(user.id, user.get_reset_token(), int(os.getenv("EXPIRE_TIME"))))
        flash(f"Check your email to continue.", "primary")
        return redirect(url_for('users.login_user'))
    return render_template("users/forget_password.html", form=form)


@users.route("/reset_password/<int:id>/<string:token>", methods=["GET", "POST"])
def reset_password(id: int, token: str):
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    # Verifying the token
    veridication_result = User.verify_reset_key(
        id, token, int(os.getenv("EXPIRE_TIME")))
    if not veridication_result["is_authenticate"]:
        return render_template("mains/errors.html", status=400, message=f"{veridication_result['message']}")
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        user = User.query.get(id)
        user.password = hashed_password
        db.session.commit()
        flash(f"{veridication_result['message']}", "success")
        return redirect(url_for("users.login_user"))
    return render_template("users/reset_password.html", form=form)


@users.route("/view-profile")
@login_required
def view_user_profile():
    return redirect(url_for("profiles.view_profile", id=current_user.id))


@users.route("/report/<int:id>", methods=["POST"])
@login_required
@is_verified
def report_user(id: int):
    user = User.query.get(id)
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for("profiles.view_profile", id=id))
    category = request.form.get("report-category")
    text = request.form.get("report-text")
    if category == "":
        flash("Please add a category of your report.", "danger")
    else:
        report_category = None
        if category == ComplainCategory.CHEATER:
            report_category = ComplainCategory.CHEATER
        elif category == ComplainCategory.HARASSMENT:
            report_category = ComplainCategory.HARASSMENT
        elif category == ComplainCategory.SCAMMER:
            report_category = ComplainCategory.SCAMMER
        else:
            report_category = ComplainCategory.OTHER
        complain = Complain(text, report_category,
                            current_user.profile.id, user.profile.id)
        db.session.add(complain)
        # push notification
        users = User.query.filter_by(role=Role.ADMIN).all()
        for u in users:
            notification = Notification(
                NotificationMessage.report_user(
                    current_user.profile.get_fullname(), user.profile.get_fullname()
                ),
                url_for("admins.complain_box"),
                u.profile.id
            )
            db.session.add(notification)
        db.session.commit()
        flash("Successfully reported the profile.", "success")
    return redirect(url_for("profiles.view_profile", id=id))


@users.route("/resend-token")
@login_required
@is_unbanned
def resend_token():
    generated_token_for_email = generate_token(6)
    hashed_token = bcrypt.generate_password_hash(
        generated_token_for_email).decode("utf-8")
    current_user.verified_code = hashed_token
    db.session.commit()
    # Sending email
    send_mail(current_user.email, "Email Verification Code",
              f"Your Token is {generated_token_for_email}")
    flash("A new verification token has been sent to your email address.", "success")
    return redirect(url_for("profiles.verify_email"))

flaskr/templates/components/navigation.html
<nav class="navbar navbar-expand-lg navbar-light navigation-bar">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('mains.homepage') }}">
            <img src="{{ url_for('static', filename='images/default/Logos/FINDER-Light.png') }}" alt="Brand Logo"
                class="nav-brand-logo">
        </a>
        <div class="nav-item sm-screen">
            <form action="{{ url_for('mains.search') }}" method="post" class="d-flex">
                {{ s_form.hidden_tag() }}
                {{ s_form.search(class="form-control search-bar", id="search") }}
                {{ s_form.submit(class="btn search-btn") }}
            </form>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars nav-menu-three-bar"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="nav-item ms-4 big-screen">
                    <form action="{{ url_for('mains.search') }}" method="post" class="d-flex">
                        {{ s_form.hidden_tag() }}
                        {{ s_form.search(class="form-control search-bar-sm", id="search") }}
                        {{ s_form.submit(class="btn search-btn") }}
                    </form>
                </div>
                <ul class="navbar-nav ms-auto mb-lg-0 big-screen">
                    <div class="d-flex {{'d-none' if not current_user.is_authenticated}}">
                        <li class="nav-item me-1">
                            {% if current_user.role and current_user.role.value == "host" %}
                            <a href="{{ url_for('events.create_event') }}" type="button"
                                class="btn btn-infos position-relative" title="Create a event">
                                <i class="fas fa-plus"></i>
                            </a>
                            {% elif current_user.role and current_user.role.value == "admin" %}
                            <a href="{{ url_for('events.create_event') }}" type="button"
                                class="btn btn-infos position-relative" title="Create a event">
                                <i class="fas fa-plus"></i>
                            </a>
                            <a href="{{ url_for('admins.dashboard') }}" type="button"
                                class="btn btn-infos position-relative" title="Admin dashboard">
                                <i class="fas fa-user-shield"></i>
                            </a>
                            {% else %}
                            <a href="{{ url_for('profiles.req_for_host') }}" type="button"
                                class="btn btn-infos position-relative" title="Apply for host">
                                <i class="fas fa-user-tie"></i>
                            </a>
                            {% endif %}
                        </li>
                        {% if current_user.profile %}
                        <li class="nav-item me-1">
                            <a href="{{ url_for('notifications.get_notifications') }}" type="button"
                                class="btn btn-infos position-relative">
                                <i class="bi bi-bell-fill"></i>
                                <span
                                    class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                    {{ current_user.profile.total_unreaded_notifications() }}
                                    <span class="visually-hidden">unread notifications</span>
                                </span>
                            </a>
                        </li>
                        {% endif %}
                        <div class="btn-group ms-2">
                            <a href="#" class="btn btn-infos dropdown-toggle" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                <i class="bi bi-person-bounding-box"></i>
                                {% if current_user.is_authenticated %}
                                <span class="ms-1">{{ current_user.profile.get_fullname() }}</span>
                                {% else %}
                                <span class="ms-1">Anonymous</span>
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{{ url_for('users.view_user_profile') }}">
                                        <i class="bi bi-binoculars-fill"></i>
                                        <span class="ms-1">View Profile</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <i class="bi bi-chat-right-dots-fill"></i>
                                        <span class="ms-1">Messages</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ url_for('profiles.change_profile_info') }}">
                                        <i class="bi bi-gear-wide-connected"></i>
                                        <span class="ms-1">Account Settings</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ url_for('profiles.bookmarks') }}">
                                        <i class="bi bi-journal-bookmark-fill"></i>
                                        <span class="ms-1">Bookmarks</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ url_for('profiles.events') }}">
                                        <i class="bi bi-calendar2-event-fill"></i>
                                        <span class="ms-1">Your Events</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ url_for('profiles.view_complains') }}">
                                        <i class="bi bi-exclamation-triangle-fill"></i>
                                        <span class="ms-1">Complains</span>
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a href="{{ url_for('users.logout_user') }}" class="dropdown-item">
                                        <i class="bi bi-box-arrow-left"></i>
                                        <span class="ms-1">Logout</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="d-flex {{'d-none' if current_user.is_authenticated}}">
                        <li class="nav-item me-1">
                            <a href="{{ url_for('users.register_user') }}"
                                class="btn btn-auth {{ 'btn-active' if active == 'register' }}">Register</a>
                            <a href="{{ url_for('users.login_user') }}"
                                class="btn btn-auth {{ 'btn-active' if active == 'login' }}">Login</a>
                        </li>
                    </div>
                </ul>
                <div class="d-flex flex-column">
                    <form action="{{ url_for('mains.search') }}" method="post" class="d-flex flex-row xsm-screen">
                        {{ s_form.hidden_tag() }}
                        {{ s_form.search(class="form-control search-bar-sm", id="search") }}
                        {{ s_form.submit(class="btn search-btn-sm") }}
                    </form>
                    <div class="d-flex flex-column sm-screen {{'d-none' if not current_user.is_authenticated}}">
                        {% if current_user.role and current_user.role.value == "host" %}
                        <a href="{{ url_for('events.create_event') }}" type="button" class="btn mt-1 btn-infos">
                            <i class="fas fa-plus"></i>
                            <span class="ms-1">Create Event</span>
                        </a>
                        {% elif current_user.role and current_user.role.value == "admin" %}
                        <a href="{{ url_for('events.create_event') }}" type="button" class="btn mt-1 btn-infos">
                            <i class="fas fa-plus"></i>
                            <span class="ms-1">Create Event</span>
                        </a>
                        <a href="{{ url_for('admins.dashboard') }}" type="button" class="btn mt-1 btn-infos">
                            <i class="fas fa-user-shield"></i>
                            <span class="ms-1">Admin Dashboard</span>
                        </a>
                        {% else %}
                        <a href="{{ url_for('profiles.req_for_host') }}" type="button" class="btn mt-1 btn-infos">
                            <i class="fas fa-user-tie"></i>
                            <span class="ms-1">Apply for Host</span>
                        </a>
                        {% endif %}
                        {% if current_user.profile %}
                        <a href="{{ url_for('notifications.get_notifications') }}" class="btn mt-1 btn-infos">
                            <i class="bi bi-bell-fill"></i>
                            {% if current_user.profile.total_unreaded_notifications() != 0 %}
                            <span class="ms-1">View Notifications <span class="text-danger">({{
                                    current_user.profile.total_unreaded_notifications() }})</span></span>
                            {% else %}
                            <span class="ms-1">View Notifications</span>
                            {% endif %}
                        </a>
                        {% endif %}
                        <a href="{{ url_for('users.view_user_profile') }}" class="btn mt-1 btn-infos">
                            <i class="bi bi-binoculars-fill"></i>
                            <span class="ms-1">View Profile</span>
                        </a>
                        <a href="#" class="btn mt-1 btn-infos">
                            <i class="bi bi-chat-right-dots-fill"></i>
                            <span class="ms-1">Messages</span>
                        </a>
                        <a href="{{ url_for('profiles.change_profile_info') }}" class="btn mt-1 btn-infos">
                            <i class="bi bi-gear-wide-connected"></i>
                            <span class="ms-1">Account Settings</span>
                        </a>
                        <a href="{{ url_for('profiles.bookmarks') }}" class="btn mt-1 btn-infos">
                            <i class="bi bi-journal-bookmark-fill"></i>
                            <span class="ms-1">Bookmarks</span>
                        </a>
                        <a href="{{ url_for('profiles.events') }}" class="btn mt-1 btn-infos">
                            <i class="bi bi-calendar2-event-fill"></i>
                            <span class="ms-1">Your Events</span>
                        </a>
                        <a href="{{ url_for('profiles.view_complains') }}" class="btn mt-1 btn-infos">
                            <i class="bi bi-exclamation-triangle-fill"></i>
                            <span class="ms-1">Complains</span>
                        </a>
                        <a href="#" class="btn mt-1 btn-infos">
                            <i class="bi bi-pc-display"></i>
                            <span class="ms-1">Admin Dashboard</span>
                        </a>
                        <a href="{{ url_for('users.logout_user') }}" class="btn mt-1 btn-infos">
                            <i class="bi bi-box-arrow-left"></i>
                            <span class="ms-1">Logout</span>
                        </a>
                    </div>
                    <div class="d-flex flex-column sm-screen {{'d-none' if current_user.is_authenticated}}">
                        <a href="{{ url_for('users.register_user') }}"
                            class="btn mt-1 btn-auth {{ 'btn-active' if active == 'register' }}">Register</a>
                        <a href="{{ url_for('users.login_user') }}"
                            class="btn mt-1 btn-auth {{ 'btn-active' if active == 'login' }}">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

flaskr/templates/components/toast.html
<div class="toast-container position-fixed top-0 start-0 p-3" style="z-index: 101;">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header align-items-center bg-{{ category }} text-{{ 'light' if category != 'info' and category != 'warning' else 'dark' }}">
            <p class="me-auto my-0">{{ "Event Finder" }}</p>
            <small class="me-2">Message</small>
            <button type="button" class="m-0 btn btn-sm btn-{{ category }}" data-bs-dismiss="toast" aria-label="Close">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <div class="toast-body">
            {{ message }}
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>

flaskr/templates/components/validation.html
{% if eligable %}
{% if eligable.get("is_banned") %}
<div class="container mt-1">
    <div class="row">
        <div class="col-12">
            <div class="alert alert-danger mb-0">Your account has been banned. Come back after {{
                current_user.profile.banned.days_left() }}</div>
        </div>
    </div>
</div>
{% elif not eligable.get("is_valid") %}
<div class="container mt-1">
    <div class="row">
        <div class="col-12">
            <div class="alert alert-warning d-flex mb-0">
                <p class="my-0 align-self-center flex-grow-1">Your account is not validated. Please verify the
                    account by entering the code which was sent to your email address while creating the account.
                </p>
                <a href="{{ url_for('profiles.verify_email') }}" class="btn btn-sm btn-warning align-self-center ms-1"
                    style="width: 100px;">Verify</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endif %}