flaskr/events/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flaskr import db
from flaskr.decorators import is_host, is_verified
from flaskr.events.forms import *
from flaskr.models import (Decline, Event, Notification, PaymentPending, Post,
                           Profile)
from flaskr.notifications.utils import NotificationMessage
from flaskr.profiles.utils import remove_photo, save_photos
from sqlalchemy import desc

events = Blueprint("events", __name__, url_prefix="/events")


@events.route("/")
def get_events():
    all_events = Event.query.order_by(desc(Event.created_at)).all()
    return render_template("events/events.html", events=all_events, len=len)


@events.route("/<int:id>")
def view_event(id: int):
    event = Event.query.get(id)
    if not event:
        return render_template("mains/errors.html", status=404, message="Event not found!")
    query_str = request.args.get("filter")
    members_sub_query = request.args.get("members")
    recive_number = event.phone_number or "01xxxxxxxxx"

    if query_str == "messages":
        return render_template("events/view-event/messages.html",
                               len=len, str=str, event=event,
                               active='messages', recive_number=recive_number)
    if query_str == "members":
        sub_menu = "members"
        if members_sub_query == "pending":
            sub_menu = "pending-members"
        elif members_sub_query == "decline":
            sub_menu = "decline-members"
        return render_template("events/view-event/members.html",
                               len=len, str=str, event=event,
                               active="members", sub_menu=sub_menu,
                               recive_number=recive_number)
    if query_str == "posts":
        posts = Post.query.filter_by(event_id=id).order_by(desc(Post.created_at)).all()
        return render_template("events/view-event/posts.html",
                               len=len, str=str, event=event,
                               active='posts', recive_number=recive_number,
                               posts=posts)
    # if none of the avobe is true
    return render_template("events/view-event/details.html",
                           len=len, str=str, event=event,
                           active='details', recive_number=recive_number)


@events.route("/create", methods=["GET", "POST"])
@login_required
@is_verified
@is_host
def create_event():
    form = EventForm()
    if form.validate_on_submit():
        event = Event(form.event_title.data, form.event_description.data, form.event_location.data,
                      form.event_start_time.data, form.event_days_count.data, form.event_nights_count.data,
                      form.event_fee.data, current_user.profile.id, form.event_cover_photo.data,
                      form.event_max_members.data, form.hotel_name.data, form.hotel_web_link.data, form.phone_number.data)
        if form.event_cover_photo.data:
            # saving
            photo_file = save_photos(
                form.event_cover_photo.data, event.id, "eventCover", 1180, 450)
            event.cover_photo = "/images/uploads/eventCover/" + photo_file
        db.session.add(event)
        db.session.commit()
        current_user.profile.add_joined_events(event.id)
        flash(f"Event information saved", "success")
        return redirect(url_for("events.view_event", id=event.id))
    return render_template("events/create-event.html", form=form)


@events.route("/settings/info/<int:id>", methods=["GET", "POST"])
@login_required
def event_info(id: int):
    event = Event.query.get(id)
    if not event:
        return render_template("mains/errors.html", status=404, message="Event not found!")
    if event.host.id != current_user.profile.id:
        flash("Only the host can access this route", "danger")
        return redirect(url_for("events.view_event", id=event.id))
    form = EventForm()
    if request.method == "POST":
        # post request
        event.title = form.event_title.data
        event.description = form.event_description.data
        event.place_name = form.event_location.data
        event.event_time = form.event_start_time.data
        event.day = form.event_days_count.data
        event.night = form.event_nights_count.data
        event.fee = form.event_fee.data
        event.hotel_name = form.hotel_name.data
        event.hotel_weblink = form.hotel_web_link.data
        event.phone_number = form.phone_number.data
        if form.event_cover_photo.data:
            file_path = event.cover_photo
            if not ("/images/default/CoverPhotos/event-default.png" in file_path):
                remove_photo(file_path)
            # saving
            photo_file = save_photos(
                form.event_cover_photo.data, event.id, "eventCover", 1180, 450)
            event.cover_photo = "/images/uploads/eventCover/" + photo_file
        db.session.commit()
        flash(f"Event information saved", "success")
    # add the values
    elif request.method == "GET":
        form.event_title.data = event.title
        form.event_description.data = event.description
        form.event_location.data = event.place_name
        form.event_start_time.data = event.event_time
        form.event_days_count.data = event.day
        form.event_nights_count.data = event.night
        form.event_fee.data = event.fee
        form.hotel_name.data = event.hotel_name
        form.hotel_web_link.data = event.hotel_weblink
        form.phone_number.data = event.phone_number
    return render_template("events/event-info.html", active="event-info", form=form, event=event)


@events.route("/settings/plans/<int:id>", methods=["GET", "POST"])
@login_required
def event_plans(id: int):
    event = Event.query.get(id)
    if event.host.id != current_user.profile.id:
        flash("Only the host can access this route", "danger")
        return redirect(url_for("events.view_event", id=event.id))
    if request.method == "POST":
        list_of_plans = []
        for i in range(event.day+event.night):
            list_of_plans.append(request.form.get(f"event_plans_{i}"))
        event.plans = list_of_plans
        db.session.commit()
        flash("Event updated successfully.", "success")
    return render_template("events/edit-plans.html", active="event-plans", event=event)


@events.route("/upload/<int:id>", methods=["POST"])
@login_required
def add_photos(id: int):
    event = Event.query.get(id)
    if not event:
        return render_template("mains/errors.html", status=404, message="Event not found!")
    if event.host.id != current_user.profile.id:
        flash("Only the host can access this route", "danger")
        return redirect(url_for("events.view_event", id=event.id))
    photo_1 = request.files.get("photo_1")
    photo_2 = request.files.get("photo_2")
    photo_3 = request.files.get("photo_3")

    if photo_1:
        photo_file = save_photos(
            photo_1, event.id, "eventPhotos", 1280, 720)
        event.add_photo("/images/uploads/eventPhotos/" + photo_file)

    if photo_2:
        photo_file = save_photos(
            photo_2, event.id, "eventPhotos", 1280, 720)
        event.add_photo("/images/uploads/eventPhotos/" + photo_file)

    if photo_3:
        photo_file = save_photos(
            photo_3, event.id, "eventPhotos", 1280, 720)
        event.add_photo("/images/uploads/eventPhotos/" + photo_file)

    flash("Photos uploaded successfully.", "success")
    return redirect(url_for("events.view_event", id=event.id))


@events.route("/register/<int:id>", methods=["POST"])
@login_required
def register_for_event(id: int):
    trnx_id = request.form.get("trnx_id")
    event = Event.query.get(id)
    if not event:
        flash("Event not found!", "danger")
        return redirect(url_for("mains.homepage"))
    if not trnx_id:
        return redirect(url_for("events.view_event", id=id))
    if not event.event_status().get("status"):
        flash("Registration closed.", "danger")
        return redirect(url_for("events.view_event", id=id))
    pending = PaymentPending(trnx_id, current_user.profile.id, id)
    db.session.add(pending)
    notify = Notification(NotificationMessage.pending_payments(current_user.profile.get_fullname(
    )), url_for("events.view_event", id=id, filter="members", members="pending"), event.host.id)
    db.session.add(notify)
    db.session.commit()
    flash("Request successfully sent.", "success")
    return redirect(url_for("events.view_event", id=id))


@events.route("/<int:event_id>/accept/<int:profile_id>")
@login_required
def accept_pending_members(event_id: int, profile_id: int):
    event = Event.query.get(event_id)
    profile = Profile.query.get(profile_id)
    
    if not event:
        flash("Event not found!.", "danger")
        return redirect(url_for("events.view_event", id=event_id, filter="members", members="pending"))
    
    if not profile:
        flash("Profile not found!.", "danger")
        return redirect(url_for("events.view_event", id=event_id, filter="members", members="pending"))
    
    if current_user.profile.id != event.host.id:
        flash("You can not access the route.", "danger")
        return redirect(url_for("events.view_event", id=event_id, filter="members", members="pending"))
    pending_payments = event.pending_payments
    for i in pending_payments:
        if profile_id == i.profile.id:
            i.approve()
            if i.decline:
                i.decline.resolve()
            break
    event.add_members(profile_id)
    profile.add_joined_events(event.id)
    notification = Notification(NotificationMessage.approve_event_registration(),
                                url_for("events.view_event", id=event.id),
                                profile_id)
    db.session.add(notification)
    db.session.commit()
    flash("Member approved.", "info")

flaskr/users/routes.py
import os

from flask import (Blueprint, flash, redirect, render_template, request,
                   session, url_for)
from flask_login import current_user, login_required
from flask_login import login_user as login_user_function
from flask_login import logout_user as logout_user_function
from flaskr import app, bcrypt, db
from flaskr.decorators import is_admin, is_unbanned, is_verified
from flaskr.mails import send_mail
from flaskr.models import (Complain, ComplainCategory, Event, Notification,
                           Profile, Role, User)
from flaskr.notifications.utils import NotificationMessage
from flaskr.users.forms import *
from flaskr.users.utils import generate_token, password_reset_key_mail_body
from jwt import encode

users = Blueprint("users", __name__, url_prefix="/users")


@users.route("/")
@login_required
@is_admin
def get_users():
    all_users = User.query.all()
    return render_template("users/view_all_user.html", users=all_users)


@users.route("/register", methods=["GET", "POST"])
def register_user():
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    form = RegisterForm()
    if form.validate_on_submit():
        # Generating token
        generated_token_for_email = generate_token(6)
        # Hashing
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        hashed_token = bcrypt.generate_password_hash(
            generated_token_for_email).decode("utf-8")
        # Creating user
        all_users = User.query.all()
        user = None
        if len(all_users) == 0:
            user = User(form.email.data, hashed_password,
                        hashed_token, Role.ADMIN)
        else:
            user = User(form.email.data, hashed_password,
                        hashed_token, Role.GENERAL)
        db.session.add(user)
        db.session.commit()
        # Creating profile
        profile = Profile(form.first_name.data, form.last_name.data,
                          form.dob.data, form.gender.data, user.id)
        db.session.add(profile)
        db.session.commit()
        # Sending email
        send_mail(user.email, "Email Verification Code",
                  f"Your Token is {generated_token_for_email}")
        fetched_user = User.query.filter_by(id=user.id).first()
        flash(
            f"Account created for {fetched_user.profile.first_name} {fetched_user.profile.last_name}", "success")
        return redirect(url_for("users.login_user"))
    return render_template("users/register.html", form=form, active='register')


@users.route("/login", methods=["GET", "POST"])
def login_user():
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    form = LoginForm()
    if form.validate_on_submit():
        # Fetching the user
        fetched_user = User.query.filter_by(email=form.email.data).first()
        # Checking the email and password
        if fetched_user and bcrypt.check_password_hash(fetched_user.password, form.password.data):
            login_user_function(fetched_user, remember=form.remember_me.data)
            next_page = request.args.get("next")
            response = redirect(next_page) if next_page else redirect(
                url_for('mains.homepage'))
            # jtw
            jwt_token = encode({
                "id": fetched_user.id,
                "email": fetched_user.email,
            }, app.config.get("JWT_SECRET_KEY"), algorithm="HS256")
            response.set_cookie("access_token", jwt_token, max_age=60*60*30)
            flash("Login Successfull.", "success")
            return response
        else:
            flash("Login Failed! Please Check Email and Password.", "danger")
    return render_template("users/login.html", form=form, active='login')


@users.route("/logout")
@login_required
def logout_user():
    logout_user_function()
    return redirect(url_for("users.login_user"))


@users.route("/forget_password", methods=["GET", "POST"])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        # Fetching the user
        user = User.query.filter_by(email=form.email.data).first()
        # Sending email
        send_mail(user.email, "Password Reset Token",
                  password_reset_key_mail_body(user.id, user.get_reset_token(), int(os.getenv("EXPIRE_TIME"))))
        flash(f"Check your email to continue.", "primary")
        return redirect(url_for('users.login_user'))
    return render_template("users/forget_password.html", form=form)


@users.route("/reset_password/<int:id>/<string:token>", methods=["GET", "POST"])
def reset_password(id: int, token: str):
    if current_user.is_authenticated:
        return redirect(url_for('mains.homepage'))
    # Verifying the token
    veridication_result = User.verify_reset_key(
        id, token, int(os.getenv("EXPIRE_TIME")))
    if not veridication_result["is_authenticate"]:
        return render_template("mains/errors.html", status=400, message=f"{veridication_result['message']}")
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        user = User.query.get(id)
        user.password = hashed_password
        db.session.commit()
        flash(f"{veridication_result['message']}", "success")
        return redirect(url_for("users.login_user"))
    return render_template("users/reset_password.html", form=form)


@users.route("/view-profile")
@login_required
def view_user_profile():
    return redirect(url_for("profiles.view_profile", id=current_user.id))


@users.route("/report/<int:id>", methods=["POST"])
@login_required
@is_verified
def report_user(id: int):
    user = User.query.get(id)
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for("profiles.view_profile", id=id))
    category = request.form.get("report-category")
    text = request.form.get("report-text")
    if category == "":
        flash("Please add a category of your report.", "danger")
    else:
        report_category = None
        if category == ComplainCategory.CHEATER:
            report_category = ComplainCategory.CHEATER
        elif category == ComplainCategory.HARASSMENT:
            report_category = ComplainCategory.HARASSMENT
        elif category == ComplainCategory.SCAMMER:
            report_category = ComplainCategory.SCAMMER
        else:
            report_category = ComplainCategory.OTHER
        complain = Complain(text, report_category,
                            current_user.profile.id, user.profile.id)
        db.session.add(complain)
        # push notification
        users = User.query.filter_by(role=Role.ADMIN).all()
        for u in users:
            notification = Notification(
                NotificationMessage.report_user(
                    current_user.profile.get_fullname(), user.profile.get_fullname()
                ),
                url_for("admins.complain_box"),
                u.profile.id
            )
            db.session.add(notification)
        db.session.commit()
        flash("Successfully reported the profile.", "success")
    return redirect(url_for("profiles.view_profile", id=id))


@users.route("/resend-token")
@login_required
@is_unbanned
def resend_token():
    generated_token_for_email = generate_token(6)
    hashed_token = bcrypt.generate_password_hash(
        generated_token_for_email).decode("utf-8")
    current_user.verified_code = hashed_token
    db.session.commit()
    # Sending email
    send_mail(current_user.email, "Email Verification Code",
              f"Your Token is {generated_token_for_email}")
    flash("A new verification token has been sent to your email address.", "success")
    return redirect(url_for("profiles.verify_email"))

flaskr/templates/admins/admin-layout.html
{% extends "layout.html" %}

{% block add_styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/admins/base.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/admins/dashboard.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/admins/complain-box.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/admins/pending-request.css') }}">
{% endblock %}

{% block content %}
<div class="container mt-1">
    <div class="row">
        <div class="col-md-4">
            <div class="container">
                <div class="col-10 offset-1">
                    <ul class="list-group text-center list-group-custom">
                        <a href="{{ url_for('admins.dashboard') }}"
                            class="list-group-item btn btn-settings my-1 {{ 'btn-settings-active' if active == 'dashboard' }}">
                            Dashboard
                        </a>
                        <a href="{{ url_for('admins.pending_request') }}"
                            class="list-group-item btn btn-settings my-1 {{ 'btn-settings-active' if active == 'pending_request' }}">
                            Pending Request
                        </a>
                        <a href="{{ url_for('admins.view_hosts') }}"
                            class="list-group-item btn btn-settings my-1 {{ 'btn-settings-active' if active == 'view_hosts' }}">
                            View Hosts
                        </a>
                        <a href="{{ url_for('admins.complain_box') }}"
                            class="list-group-item btn btn-settings my-1 {{ 'btn-settings-active' if active == 'complain_box' }}">
                            Complain Box
                        </a>
                        <a href="{{ url_for('admins.log') }}"
                            class="list-group-item btn btn-settings my-1 {{ 'btn-settings-active' if active == 'log' }}">
                            Log
                        </a>
                        <a href="{{ url_for('admins.banned_users') }}"
                            class="list-group-item btn btn-settings my-1 {{ 'btn-settings-active' if active == 'banned_users' }}">
                            Banned Users
                        </a>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8 mt-1">
            {% block admin_contents %} {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

flaskr/templates/admins/banned-users.html
{% extends "admins/admin-layout.html" %}

{% block title %} Banned users {% endblock %}

{% block admin_contents %}
{% if total_acc_restriction == 0 %}
<p class="empty-status">There is no banned user</p>
{% else %}
<!-- Profile Cards Loop -->
{% for acc_restriction in acc_restrictions %}
<div class="card card-body shadow-card mb-2">
    <div class="d-flex flex-row">
        <div class="d-flex flex-row align-self-center flex-grow-1">
            <img src="{{ url_for('static', filename=acc_restriction.profile.profile_photo) }}" alt=""
                class="card-img align-self-center">
            <a href="{{ url_for('profiles.view_profile', id=acc_restriction.profile.id) }}"
                class="d-flex flex-column align-self-center card-link-custom ms-3">
                <h2 class="card-title-custom my-0">{{ acc_restriction.profile.get_fullname() }}</h2>
                <p class="card-body-custom my-0 text-muted">{{ acc_restriction.profile.user.email }}</p>
                <p class="card-body-custom my-0"><i class="fas fa-external-link-alt"></i></p>
            </a>
        </div>
        <div class="me-2 align-self-center">
            <a href="{{ url_for('admins.unban_user', id=acc_restriction.profile.user.id) }}"
                class="btn btn-sm btn-primary">Unban</a>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

flaskr/templates/admins/dashboard.html
{% extends "admins/admin-layout.html" %}

{% block title %} Admin dashboard {% endblock %}

{% block admin_contents %}
<div class="card card-body shadow-card system-status">
    System Status
</div>
<div class="row mt-3">
    <div class="text-center">
        <div id="piechart"></div>
    </div>

</div>
<div class="row mt-3">
    <div class="col-md-6">
        <a href="{{ url_for('admins.pending_request') }}" class="card-link-a">
            <div class="card card-body card-link">
                <div class="d-flex flex-column">
                    <div class="ms-auto"><i class="fas fa-external-link-alt"></i></div>
                    <div class="text-center card-details">{{ length_of_req_pending }}</div>
                    <div class="text-center">Total Pending Approvals</div>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-6">
        <a href="{{ url_for('admins.complain_box') }}" class="card-link-a">
            <div class="card card-body card-link">
                <div class="d-flex flex-column">
                    <div class="ms-auto"><i class="fas fa-external-link-alt"></i></div>
                    <div class="text-center card-details">{{ length_of_complains }}</div>
                    <div class="text-center">Total Unsolve Complains</div>
                </div>
            </div>
        </a>
    </div>
</div>
<div class="mt-3">
    <form action="{{ url_for('admins.get_profile_by_profile_id') }}" class="d-flex" method="POST">
        <input class="form-control me-2 input-box" type="text" placeholder="Enter the profile ID"
            name="get_by_profile_id">
        <button class="btn btn-dark btn-search" type="submit">Get User by Profile ID</button>
    </form>
    <form action="{{ url_for('admins.get_profile_by_user_id') }}" class="d-flex mt-2" method="POST">
        <input class="form-control me-2 input-box" type="text" placeholder="Enter the user ID" name="get_by_user_id">
        <button class="btn btn-dark btn-search" type="submit">Get User by User ID</button>
    </form>
    <form action="{{ url_for('admins.get_profile_by_email_id') }}" class="d-flex mt-2" method="POST">
        <input class="form-control me-2 input-box" type="email" placeholder="Enter the user email address"
            name="get_by_email_id">
        <button class="btn btn-dark btn-search" type="submit">Get User by Email</button>
    </form>
    <form action="{{ url_for('admins.get_profile_by_nid_id') }}" class="d-flex mt-2" method="POST">
        <input class="form-control me-2 input-box" type="text" placeholder="Enter the user NID number"
            name="get_by_nid_id">
        <button class="btn btn-dark btn-search" type="submit">Get User by NID</button>
    </form>
    <!-- Users -->
    <div class="d-flex align-items-center mt-4 mb-3">
        <div class="flex-grow-1">
            <h1 class="profile-header user-font">New Users</h1>
        </div>
        <a href="{{url_for('users.get_users')}}" class="text-reset">View all</a>
    </div>
    <div class="row">
        {% for user in users %}
        <div class="mb-2 col-md-12 col-lg-6">
            <div class="px-1">
                <div class="card card-body shadow-card">
                    <div class="d-flex flex-row">
                        <img src="{{ url_for('static', filename=user.profile.profile_photo) }}" alt=""
                            class="card-img align-self-center">
                        <a href="{{ url_for('profiles.view_profile', id=user.profile.id) }}"
                            class="d-flex flex-column align-self-center card-link-custom ms-3">
                            <h2 class="card-title-custom my-0">{{ user.profile.get_fullname() }}</h2>
                            <p class="card-body-custom my-0 text-muted">Joined on {{ user.get_joindate() }}</p>
                            <p class="card-body-custom my-0"><i class="fas fa-external-link-alt"></i></p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Events -->
    <div class="d-flex align-items-center mt-4 mb-3">
        <div class="flex-grow-1">
            <h1 class="profile-header user-font">Newly created events</h1>
        </div>
        <a href="{{url_for('events.get_events')}}" class="text-reset">View all</a>
    </div>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for event in events %}
        <div class="col">
            <div class="card shadow-card event-card h-100">
                <img src="{{ url_for('static', filename=event.cover_photo) }}" class="card-img-top event-card-img"
                    alt="Cover photo of the event">
                <div class="card-body">
                    <h6 class="card-title fw-bold">{{ event.title }}</h6>
                    <div class="card-text text-{{ event.event_status().category }} fw-bold mb-1">
                        {{ event.event_status().message }}
                    </div>
                    <div class="card-text">
                        <strong>
                            <i class="fas fa-map-marker-alt"></i> Location:
                        </strong>
                        {{ event.place_name }}
                    </div>
                    <div class="card-text">
                        <strong>
                            <i class="fas fa-clock"></i> Date:
                        </strong>
                        {{ event.get_start_date() }} at {{ event.get_start_time() }}
                    </div>
                    <div class="card-text">
                        <strong>
                            <i class="fas fa-user-tie"></i> Host:
                        </strong>
                        <a href="{{ url_for('profiles.view_profile', id=event.host.id) }}" class="text-reset">
                            {{ event.host.get_fullname() }}
                        </a>
                    </div>
                    <div class="card-text">
                        <strong>
                            <i class="fas fa-money-check-alt"></i> Register Fee:
                        </strong>
                        {{ event.fee }} Taka
                    </div>
                    <div class="card-text">
                        <strong>
                            <i class="fas fa-users"></i> Members:
                        </strong>
                        {{ len(event.members) if event.members else 0 }} out of {{ event.max_member }}
                    </div>
                    <a href="{{ url_for('events.view_event', id=event.id) }}" class="btn btn-dark w-100 btn-sm mt-3">
                        Explore the event
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Scripts for Pie Chart -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Category', 'Number of users'],
                {% for key, value in data.items() %}
        ["{{key}}", {{ value }}],
            {% endfor %}
        ]);
        var options = {
            title: 'Server User Details',
            is3D: true,
        };
        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);
    }
    </script>
    {% endblock %}

flaskr/templates/admins/log.html
{% extends "admins/admin-layout.html" %}

{% block title %} Logs {% endblock %}

{% block admin_contents %}
<h2 class="settings-header">Logs</h2>
{% endblock %}

flaskr/templates/admins/pending-request.html
{% extends "admins/admin-layout.html" %}

{% block title %} Pending request {% endblock %}

{% block admin_contents %}
{% if total_requests == 0 %}
<p class="empty-status">There is no pending request available now</p>
{% else %}
<!-- Profile Cards Loop -->
{% for request in requests %}
<div class="card card-body shadow-card mb-2">
    <div class="d-flex flex-row">
        <div class="d-flex flex-row align-self-center flex-grow-1">
            <img src="{{ url_for('static', filename=request.profile.profile_photo) }}" alt=""
                class="card-img align-self-center">
            <a href="{{ url_for('profiles.view_profile', id=request.profile.id) }}"
                class="d-flex flex-column align-self-center card-link-custom ms-3">
                <h2 class="card-title-custom my-0">{{ request.profile.get_fullname() }}</h2>
                <p class="card-body-custom my-0 text-muted">{{ request.profile.user.email }}</p>
                <p class="card-body-custom my-0"><i class="fas fa-external-link-alt"></i></p>
            </a>
        </div>
        <div class="me-2 align-self-center">
            <a href="{{ url_for('admins.approve_pending_request', id=request.id) }}"
                class="btn btn-sm btn-primary">Approve</a>
            <a href="{{ url_for('admins.decline_pending_request', id=request.id) }}"
                class="btn btn-sm btn-danger">Decline</a>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}