flaskr/events/forms.py
from datetime import datetime

from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import (DateTimeLocalField, IntegerField, StringField,
                     SubmitField, TextAreaField, FileField)
from wtforms.validators import (URL, DataRequired, Length, Optional,
                                ValidationError)


class EventForm(FlaskForm):
    event_title = StringField("Event Title*", validators=[
        DataRequired(), Length(max=150, min=2)
    ], render_kw={"placeholder": "Enter a title of the event."})
    event_location = StringField("Event Location*", validators=[
        DataRequired(), Length(max=100, min=2)
    ], render_kw={"placeholder": "ex. City, Country."})
    event_start_time = DateTimeLocalField(
        "Event Start Time*", format='%Y-%m-%dT%H:%M', validators=[DataRequired()])
    event_max_members = IntegerField("Maximum Members*", validators=[DataRequired()],
                                     render_kw={"placeholder": "Enter the maximum number."})
    event_description = TextAreaField("Description*", validators=[DataRequired()],
                                      render_kw={"placeholder": "Tell about the event."})
    event_fee = IntegerField("Event Fee*", validators=[DataRequired()],
                             render_kw={"placeholder": "Enter the event fee (In Taka)."})
    event_days_count = IntegerField(
        "Number of days*", render_kw={"placeholder": "Event days."})
    event_nights_count = IntegerField(
        "Number of nights*", render_kw={"placeholder": "Event nights."})
    phone_number = StringField("Phone Number", validators=[DataRequired()],
                             render_kw={
                                 "placeholder": "Enter your phone number."
                             })
    hotel_name = StringField("Hotel Name",
                             render_kw={
                                 "placeholder": "Enter the name of hotel if the \event includes it."
                             })
    hotel_web_link = StringField("Hotel web link", validators=[Optional(), URL()],
                                 render_kw={
        "placeholder": "Enter the link of hotel. Such as facebook page link, booking.com link etc."
    })
    event_cover_photo = FileField("Event Cover Photo", validators=[
                                  FileAllowed(["jpg", "jpeg", "png"])])
    submit = SubmitField("Submit")

    def validate_hotel_web_link(self, hotel_web_link):
        if not self.hotel_name.data and hotel_web_link.data:
            raise ValidationError(
                "Cannot set the weblink if hotel name field is remains empty.")

    def validate_event_start_time(self, event_start_time):
        current_date = datetime.utcnow()
        if current_date > event_start_time.data:
            raise ValidationError("Event start date cannot be in past.")

    def validate_event_fee(self, event_fee):
        if event_fee.data and event_fee.data < 0:
            raise ValidationError("Event fee can not be a negative value.")

    def validate_event_days_count(self, event_days_count):
        if event_days_count.data and event_days_count.data < 0:
            raise ValidationError(
                "Event days count can not be a negative value.")

    def validate_event_nights_count(self, event_nights_count):
        if event_nights_count.data and event_nights_count.data < 0:
            raise ValidationError(
                "Event nights count can not be a negative value.")

flaskr/events/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flaskr import db
from flaskr.decorators import is_host, is_verified
from flaskr.events.forms import *
from flaskr.models import (Decline, Event, Notification, PaymentPending, Post,
                           Profile)
from flaskr.notifications.utils import NotificationMessage
from flaskr.profiles.utils import remove_photo, save_photos
from sqlalchemy import desc

events = Blueprint("events", __name__, url_prefix="/events")


@events.route("/")
def get_events():
    all_events = Event.query.order_by(desc(Event.created_at)).all()
    return render_template("events/events.html", events=all_events, len=len)


@events.route("/<int:id>")
def view_event(id: int):
    event = Event.query.get(id)
    if not event:
        return render_template("mains/errors.html", status=404, message="Event not found!")
    query_str = request.args.get("filter")
    members_sub_query = request.args.get("members")
    recive_number = event.phone_number or "01xxxxxxxxx"

    if query_str == "messages":
        return render_template("events/view-event/messages.html",
                               len=len, str=str, event=event,
                               active='messages', recive_number=recive_number)
    if query_str == "members":
        sub_menu = "members"
        if members_sub_query == "pending":
            sub_menu = "pending-members"
        elif members_sub_query == "decline":
            sub_menu = "decline-members"
        return render_template("events/view-event/members.html",
                               len=len, str=str, event=event,
                               active="members", sub_menu=sub_menu,
                               recive_number=recive_number)
    if query_str == "posts":
        posts = Post.query.filter_by(event_id=id).order_by(desc(Post.created_at)).all()
        return render_template("events/view-event/posts.html",
                               len=len, str=str, event=event,
                               active='posts', recive_number=recive_number,
                               posts=posts)
    # if none of the avobe is true
    return render_template("events/view-event/details.html",
                           len=len, str=str, event=event,
                           active='details', recive_number=recive_number)


@events.route("/create", methods=["GET", "POST"])
@login_required
@is_verified
@is_host
def create_event():
    form = EventForm()
    if form.validate_on_submit():
        event = Event(form.event_title.data, form.event_description.data, form.event_location.data,
                      form.event_start_time.data, form.event_days_count.data, form.event_nights_count.data,
                      form.event_fee.data, current_user.profile.id, form.event_cover_photo.data,
                      form.event_max_members.data, form.hotel_name.data, form.hotel_web_link.data, form.phone_number.data)
        if form.event_cover_photo.data:
            # saving
            photo_file = save_photos(
                form.event_cover_photo.data, event.id, "eventCover", 1180, 450)
            event.cover_photo = "/images/uploads/eventCover/" + photo_file
        db.session.add(event)
        db.session.commit()
        current_user.profile.add_joined_events(event.id)
        flash(f"Event information saved", "success")
        return redirect(url_for("events.view_event", id=event.id))
    return render_template("events/create-event.html", form=form)


@events.route("/settings/info/<int:id>", methods=["GET", "POST"])
@login_required
def event_info(id: int):
    event = Event.query.get(id)
    if not event:
        return render_template("mains/errors.html", status=404, message="Event not found!")
    if event.host.id != current_user.profile.id:
        flash("Only the host can access this route", "danger")
        return redirect(url_for("events.view_event", id=event.id))
    form = EventForm()
    if request.method == "POST":
        # post request
        event.title = form.event_title.data
        event.description = form.event_description.data
        event.place_name = form.event_location.data
        event.event_time = form.event_start_time.data
        event.day = form.event_days_count.data
        event.night = form.event_nights_count.data
        event.fee = form.event_fee.data
        event.hotel_name = form.hotel_name.data
        event.hotel_weblink = form.hotel_web_link.data
        event.phone_number = form.phone_number.data
        if form.event_cover_photo.data:
            file_path = event.cover_photo
            if not ("/images/default/CoverPhotos/event-default.png" in file_path):
                remove_photo(file_path)
            # saving
            photo_file = save_photos(
                form.event_cover_photo.data, event.id, "eventCover", 1180, 450)
            event.cover_photo = "/images/uploads/eventCover/" + photo_file
        db.session.commit()
        flash(f"Event information saved", "success")
    # add the values
    elif request.method == "GET":
        form.event_title.data = event.title
        form.event_description.data = event.description
        form.event_location.data = event.place_name
        form.event_start_time.data = event.event_time
        form.event_days_count.data = event.day
        form.event_nights_count.data = event.night
        form.event_fee.data = event.fee
        form.hotel_name.data = event.hotel_name
        form.hotel_web_link.data = event.hotel_weblink
        form.phone_number.data = event.phone_number
    return render_template("events/event-info.html", active="event-info", form=form, event=event)


@events.route("/settings/plans/<int:id>", methods=["GET", "POST"])
@login_required
def event_plans(id: int):
    event = Event.query.get(id)
    if event.host.id != current_user.profile.id:
        flash("Only the host can access this route", "danger")
        return redirect(url_for("events.view_event", id=event.id))
    if request.method == "POST":
        list_of_plans = []
        for i in range(event.day+event.night):
            list_of_plans.append(request.form.get(f"event_plans_{i}"))
        event.plans = list_of_plans
        db.session.commit()
        flash("Event updated successfully.", "success")
    return render_template("events/edit-plans.html", active="event-plans", event=event)


@events.route("/upload/<int:id>", methods=["POST"])
@login_required
def add_photos(id: int):
    event = Event.query.get(id)
    if not event:
        return render_template("mains/errors.html", status=404, message="Event not found!")
    if event.host.id != current_user.profile.id:
        flash("Only the host can access this route", "danger")
        return redirect(url_for("events.view_event", id=event.id))
    photo_1 = request.files.get("photo_1")
    photo_2 = request.files.get("photo_2")
    photo_3 = request.files.get("photo_3")

    if photo_1:
        photo_file = save_photos(
            photo_1, event.id, "eventPhotos", 1280, 720)
        event.add_photo("/images/uploads/eventPhotos/" + photo_file)

    if photo_2:
        photo_file = save_photos(
            photo_2, event.id, "eventPhotos", 1280, 720)
        event.add_photo("/images/uploads/eventPhotos/" + photo_file)

    if photo_3:
        photo_file = save_photos(
            photo_3, event.id, "eventPhotos", 1280, 720)
        event.add_photo("/images/uploads/eventPhotos/" + photo_file)

    flash("Photos uploaded successfully.", "success")
    return redirect(url_for("events.view_event", id=event.id))


@events.route("/register/<int:id>", methods=["POST"])
@login_required
def register_for_event(id: int):
    trnx_id = request.form.get("trnx_id")
    event = Event.query.get(id)
    if not event:
        flash("Event not found!", "danger")
        return redirect(url_for("mains.homepage"))
    if not trnx_id:
        return redirect(url_for("events.view_event", id=id))
    if not event.event_status().get("status"):
        flash("Registration closed.", "danger")
        return redirect(url_for("events.view_event", id=id))
    pending = PaymentPending(trnx_id, current_user.profile.id, id)
    db.session.add(pending)
    notify = Notification(NotificationMessage.pending_payments(current_user.profile.get_fullname(
    )), url_for("events.view_event", id=id, filter="members", members="pending"), event.host.id)
    db.session.add(notify)
    db.session.commit()
    flash("Request successfully sent.", "success")
    return redirect(url_for("events.view_event", id=id))


@events.route("/<int:event_id>/accept/<int:profile_id>")
@login_required
def accept_pending_members(event_id: int, profile_id: int):
    event = Event.query.get(event_id)
    profile = Profile.query.get(profile_id)
    
    if not event:
        flash("Event not found!.", "danger")
        return redirect(url_for("events.view_event", id=event_id, filter="members", members="pending"))
    
    if not profile:
        flash("Profile not found!.", "danger")
        return redirect(url_for("events.view_event", id=event_id, filter="members", members="pending"))
    
    if current_user.profile.id != event.host.id:
        flash("You can not access the route.", "danger")
        return redirect(url_for("events.view_event", id=event_id, filter="members", members="pending"))
    pending_payments = event.pending_payments
    for i in pending_payments:
        if profile_id == i.profile.id:
            i.approve()
            if i.decline:
                i.decline.resolve()
            break
    event.add_members(profile_id)
    profile.add_joined_events(event.id)
    notification = Notification(NotificationMessage.approve_event_registration(),
                                url_for("events.view_event", id=event.id),
                                profile_id)
    db.session.add(notification)
    db.session.commit()
    flash("Member approved.", "info")

flaskr/templates/events/view-event/details.html
{% extends "events/view-event/view-event-layout.html" %}
{% block title %} Event Details {% endblock %}

{% block event_data %}
<div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col">
        <!-- About the event -->
        <div class="card card-body shadow-card h-100">
            <div class="event-status-top-bar d-flex">
                <div class="fw-bold">About the event</div>
                {% if current_user.profile and event.host.id == current_user.profile.id %}
                <a href="{{ url_for('events.event_info', id=event.id) }}"
                    class="align-self-center ms-auto icon-dark link-icon-dark">
                    <i class="fas fa-cog my-auto sm-icon"></i>
                </a>
                {% endif %}
            </div>
            <div class="px-1 mt-3">
                <div class="d-flex align-items-center">
                    <i class="fas fa-money-check-alt"></i>
                    <div class="fw-bold mx-2">Register fee:</div>
                    <div>{{ event.fee }} Taka</div>
                </div>
                <div class="d-flex align-items-center">
                    <i class="fas fa-calendar-times"></i>
                    <div class="fw-bold mx-2">Event Date:</div>
                    <div>{{ event.get_start_date() }}</div>
                </div>
                <div class="d-flex align-items-center">
                    <i class="fas fa-clock"></i>
                    <div class="fw-bold mx-2">Event Time:</div>
                    <div>{{ event.get_start_time() }}</div>
                </div>
                <div class="d-flex align-items-center">
                    <i class="fas fa-users"></i>
                    <div class="fw-bold mx-2">Members Count:</div>
                    <div>{{ len(event.members) if event.members else 0 }} out of {{ event.max_member }} going</div>
                </div>
                <div class="d-flex align-items-center">
                    <i class="far fa-comment"></i>
                    <div class="fw-bold mx-2">Total Posts:</div>
                    <div>{{ '0' if not event.posts else len(event.posts) }}</div>
                </div>
                <div class="d-flex align-items-center">
                    <i class="fas fa-hotel"></i>
                    <div class="fw-bold mx-2">Hotel Name:</div>
                    {% if event.event_weblink != '' and event.hotel_name != '' %}
                    <a class="text-dark" target="_blank" href="{{ event.hotel_weblink }}">{{ event.hotel_name }}</a>
                    {% elif event.hotel_name != '' %}
                    <div>{{ event.hotel_name }}</div>
                    {% else %}
                    <div>No hotel added</div>
                    {% endif %}
                </div>
                <hr class="my-1" style="border: 1px solid black;">
                <div class="text-{{ event.event_status().category }} my-0 fw-bold">
                    {{ event.event_status().message }}
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card card-body shadow-card  h-100">
            <div class="event-status-top-bar d-flex">
                <div class="fw-bold">Host Details</div>
            </div>
            <div class="d-flex align-items-center m-auto">
                <img src="{{ url_for('static', filename=event.host.profile_photo) }}" class="host-details-img">
                <div class="px-1 mt-3 mx-3">
                    <div class="d-flex align-items-center">
                        <i class="fas fa-address-book"></i>
                        <div class="mx-2">
                            <a href="{{ url_for('profiles.view_profile', id=event.host.id) }}"
                                class="text-dark fw-bold">{{ event.host.get_fullname() }}</a>
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <i class="fas fa-at"></i>
                        <div class="mx-2">{{ event.host.user.email }}</div>
                    </div>
                    <div class="d-flex align-items-center">
                        <i class="fas fa-tty"></i>
                        <div class="fw-bold mx-2">Contact:</div>
                        <div>{{ event.phone_number }}</div>
                    </div>
                    <div class="d-flex align-items-center">
                        <i class="fas fa-star"></i>
                        <div class="mx-2">
                            {{ event.host.user.profile.rating if event.host.user.profile.rating else
                            'Unrated'}}
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <i class="fas fa-calendar-times"></i>
                        <div class="mx-2">{{ len(event.host.hosted_events) }} event hosted</div>
                    </div>
                    <div class="d-flex align-items-center">
                        <i class="fas fa-id-card"></i>
                        <div class="mx-2">{{ event.host.nid_number }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Photos of event -->
<div class="row row-cols-1 row-cols-md-2 g-4 mt-3">
    <div class="col">
        <div class="event-status-top-bar d-flex">
            <div class="fw-bold">
                Photos
            </div>
            {% if current_user.profile and event.host.id == current_user.profile.id %}
            <button class="align-self-center ms-auto icon-dark link-icon-dark border-0" data-bs-toggle="modal"
                data-bs-target="#add-photo-modal">
                <i class="fas fa-plus sm-icon"></i>
            </button>
            {% endif %}
        </div>
        <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
            <div class="carousel-inner mt-3">
                {% for i in range(len(event.photos)) %}
                <div class="carousel-item {{ 'active' if i==0 else '' }}">
                    <img src="{{ url_for('static', filename=event.photos[i]) }}" class="d-block w-100"
                        alt="Event photo">
                </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark"
                data-bs-slide="prev">
                <span class="next-prev-slider-btn"><i class="fas fa-chevron-left" aria-hidden="true"></i></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark"
                data-bs-slide="next">
                <span class="next-prev-slider-btn"><i class="fas fa-chevron-right" aria-hidden="true"></i></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <!-- Descriptions -->
    <div class="col">
        <div class="card card-body shadow-card h-100">
            <div class="event-status-top-bar d-flex">
                <div class="fw-bold">Event Description</div>
                {% if current_user.profile and event.host.id == current_user.profile.id %}
                <a href="{{ url_for('events.event_info', id=event.id) }}"
                    class="align-self-center ms-auto icon-dark link-icon-dark">
                    <i class="fas fa-cog my-auto sm-icon"></i>
                </a>
                {% endif %}
            </div>
            <div class="mt-1 mx-2" style="text-align: justify;">{{ event.description }}</div>
        </div>
    </div>
</div>
<div class="row mt-4">
    <div class="col-md-8 offset-md-2">
        <div class="event-status-top-bar d-flex">
            <div class="fw-bold">
                Event Plannings
            </div>
            {% if current_user.profile and event.host.id == current_user.profile.id %}
            <a href="{{ url_for('events.event_plans', id=event.id) }}"
                class="align-self-center ms-auto icon-dark link-icon-dark border-0">
                <i class="fas fa-cog my-auto sm-icon"></i>
            </a>
            {% endif %}
        </div>
        {% if len(event.plans) > 0 %}
        <div class="card card-body shadow-card my-2">
            {% for i in range(len(event.plans)) %}
            {% if event.plans[i] != "" %}
            <div class="my-2">
                <div class="fw-bold day-title">
                    Day {{ i }}
                </div>
                <p>
                    {{ event.plans[i] }}
                </p>
            </div>
            <hr class="my-0" />
            {% endif %}
            {% endfor %}
        </div>
        {% else %}
        <p class="my-2 fw-bold text-center">
            The host did not add any plans yet.
        </p>
        {% endif %}
    </div>
</div>

<!-- Modal for uploading images -->
<div class="modal fade" id="add-photo-modal" tabindex="-1" aria-labelledby="add-photo-modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header modal-header-custom">
                <h5 class="modal-title" id="add-photo-modal">
                    Add photos in the event
                </h5>
                <button type="button" class="btn" data-bs-dismiss="modal" aria-label="Close"><i
                        class="bi bi-x-lg"></i></button>
            </div>
            <div class="modal-body modal-body-custom">
                <!-- Images -->
                <div class="d-flex align-content-start flex-wrap">
                    {% if len(event.get_photos()) == 0 %}
                    <p class="my-1 mx-auto text-dark">No photos uploaded yet.</p>
                    {% else %}
                    <div class="text-muted w-100 mb-1">
                        Uploaded photos
                    </div>
                    {% for photo in event.get_photos() %}
                    <img src="{{ url_for('static', filename=photo) }}" class="sm-img p-2" alt="Event photos" />
                    {% endfor %}
                    {% endif %}
                </div>
                <form action="{{ url_for('events.add_photos', id=event.id) }}" class="mt-2" method="POST"
                    enctype="multipart/form-data">
                    <div class="text-muted w-100 mb-1">
                        Upload new photos
                    </div>
                    {% for i in range(3) %}
                    <div class="form-group mb-2">
                        <label for="photo-{{ str(i+1) }}" class="text-dark">Photo {{i+1}}</label>
                        <input type="file" class="form-control input-box" name="photo_{{ str(i+1) }}"
                            id="photo-{{ str(i+1) }}" />
                    </div>
                    {% endfor %}
                    <input type="submit" value="Upload Photos" class="btn btn-primary btn-sm" />
                    <button type="button" class="btn btn-sm me-2 btn-dark" data-bs-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flaskr/templates/events/view-event/view-event-layout.html
{% extends "layout.html" %}
{% block title %} Event {% endblock %}

{% block add_styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/events/view-event.css') }}">
{% endblock %}

{% block content %}
<div class="container-fluid px-0 cover-bg">
    <div class="container cover-location">
        <img class="event-image" src="{{ url_for('static', filename=event.cover_photo) }}" alt="event_image">
        <div class="card card-body location-name">
            <span>{{ event.place_name }}</span>
        </div>
    </div>
</div>
<div class="container mt-2">
    <div class="d-flex">
        <div>
            <div class="event-time text-uppercase">
                {{ event.get_start_date_time_str() }}
            </div>
            <h1 class="event-name-style">
                {{ event.title }}
            </h1>
        </div>
        <div class="ms-auto align-self-center">
            {% if current_user.profile %}
            {% if current_user.profile and current_user.profile.is_event_bookmarked(event.id) %}
            <a href="{{ url_for('profiles.unbookmark_event', id=event.id) }}"
                title="Remove the event from bookmarked list." class="btn btn-sm btn-dark">
                <i class="fas fa-bookmark"></i>
            </a>
            {% else %}
            <a href="{{ url_for('profiles.bookmark_event', id=event.id) }}"
                title="Bookmark the event." class="btn btn-sm btn-dark">
                <i class="far fa-bookmark"></i>
            </a>
            {% endif %}
            {% endif %}
            {% if current_user.profile and current_user.profile.id == event.host.id %}
            <a href="{{ url_for('events.event_info', id=event.id) }}"
                title="Edit the events info." class="btn btn-sm btn-dark">
                <i class="fas fa-cog"></i>
            </a>
            {% endif %}
            <button class="btn btn-sm btn-dark" title="Click to copy the event link.">
                <i class="fas fa-share-alt"></i>
            </button>
            {% if current_user.profile %}
            {% if not event.event_status().status %}
            <button class="btn btn-sm btn-danger">Registration Closed</button>
            {% elif current_user.profile.id == event.host.id %}
            <button class="btn btn-sm btn-dark">Hosting</button>
            {% elif event.is_profile_going(current_user.profile.id) %}
            <button class="btn btn-sm btn-dark"><i class="fas fa-check"></i> Registered</button>
            {% elif event.is_profile_pending(current_user.profile.id) %}
            <button class="btn btn-sm btn-dark"><i class="far fa-clock"></i> Pending</button>
            {% else %}
            <button class="btn btn-sm btn-dark" data-bs-toggle="modal" data-bs-target="#event-register-modal">
                <i class="fas fa-signature"></i> Register
            </button>
            {% endif %}
            {% endif %}
        </div>
    </div>

    <ul class="nav nav-pills mt-1 mb-3">
        <li class="nav-item me-1 text-center">
            <a class="nav-link btn-sm btn-nav {{ 'active' if active == 'details' }}"
                href="{{ url_for('events.view_event', id=event.id, filter='details') }}">Details</a>
        </li>
        <li class="nav-item me-1 text-center">
            <a class="nav-link btn-sm btn-nav {{ 'active' if active == 'posts' }}"
                href="{{ url_for('events.view_event', id=event.id, filter='posts') }}">Event Posts</a>
        </li>
        <li class="nav-item me-1 text-center">
            <a class="nav-link btn-sm btn-nav {{ 'active' if active == 'messages' }}"
                href="{{ url_for('events.view_event', id=event.id, filter='messages') }}">Message Box</a>
        </li>
        <li class="nav-item me-1 text-center">
            <a class="nav-link btn-sm btn-nav {{ 'active' if active == 'members' }}"
                href="{{ url_for('events.view_event', id=event.id, filter='members') }}">Members</a>
        </li>
    </ul>

    {% block event_data %} {% endblock %}
    <!-- Register modal -->
    <div class="modal fade" id="event-register-modal" tabindex="-1" aria-labelledby="event-register-modal"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header modal-header-custom">
                    <h5 class="modal-title" id="event-register-modal">
                        Register in the event
                    </h5>
                    <button type="button" class="btn" data-bs-dismiss="modal" aria-label="Close"><i
                            class="bi bi-x-lg"></i></button>
                </div>
                <h6 class="ms-3 text-muted mb-0">Please fill out the form</h6>
                <div class="container">
                    <form action="{{ url_for('events.register_for_event', id=event.id) }}" class="mt-2 mb-4 px-2"
                        method="POST">
                        <strong class="text-highlighted">
                            Please send {{ event.fee }} taka to {{ recive_number }} via Bkash, Nagad, Ucash to procced
                            the registration.
                        </strong>
                        <div class="form-floating my-2">
                            <input type="text" class="form-control input-box" id="trxn-id" placeholder="Trxn ID" name="trnx_id">
                            <label for="trxn-id">Trxn ID</label>
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                        <button type="button" class="btn btn-sm btn-dark me-2" data-bs-dismiss="modal">Close</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}