flaskr/events/forms.py
from datetime import datetime

from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import (DateTimeLocalField, IntegerField, StringField,
                     SubmitField, TextAreaField, FileField)
from wtforms.validators import (URL, DataRequired, Length, Optional,
                                ValidationError)


class EventForm(FlaskForm):
    event_title = StringField("Event Title*", validators=[
        DataRequired(), Length(max=150, min=2)
    ], render_kw={"placeholder": "Enter a title of the event."})
    event_location = StringField("Event Location*", validators=[
        DataRequired(), Length(max=100, min=2)
    ], render_kw={"placeholder": "ex. City, Country."})
    event_start_time = DateTimeLocalField(
        "Event Start Time*", format='%Y-%m-%dT%H:%M', validators=[DataRequired()])
    event_max_members = IntegerField("Maximum Members*", validators=[DataRequired()],
                                     render_kw={"placeholder": "Enter the maximum number."})
    event_description = TextAreaField("Description*", validators=[DataRequired()],
                                      render_kw={"placeholder": "Tell about the event."})
    event_fee = IntegerField("Event Fee*", validators=[DataRequired()],
                             render_kw={"placeholder": "Enter the event fee (In Taka)."})
    event_days_count = IntegerField(
        "Number of days*", render_kw={"placeholder": "Event days."})
    event_nights_count = IntegerField(
        "Number of nights*", render_kw={"placeholder": "Event nights."})
    phone_number = StringField("Phone Number", validators=[DataRequired()],
                             render_kw={
                                 "placeholder": "Enter your phone number."
                             })
    hotel_name = StringField("Hotel Name",
                             render_kw={
                                 "placeholder": "Enter the name of hotel if the \event includes it."
                             })
    hotel_web_link = StringField("Hotel web link", validators=[Optional(), URL()],
                                 render_kw={
        "placeholder": "Enter the link of hotel. Such as facebook page link, booking.com link etc."
    })
    event_cover_photo = FileField("Event Cover Photo", validators=[
                                  FileAllowed(["jpg", "jpeg", "png"])])
    submit = SubmitField("Submit")

    def validate_hotel_web_link(self, hotel_web_link):
        if not self.hotel_name.data and hotel_web_link.data:
            raise ValidationError(
                "Cannot set the weblink if hotel name field is remains empty.")

    def validate_event_start_time(self, event_start_time):
        current_date = datetime.utcnow()
        if current_date > event_start_time.data:
            raise ValidationError("Event start date cannot be in past.")

    def validate_event_fee(self, event_fee):
        if event_fee.data and event_fee.data < 0:
            raise ValidationError("Event fee can not be a negative value.")

    def validate_event_days_count(self, event_days_count):
        if event_days_count.data and event_days_count.data < 0:
            raise ValidationError(
                "Event days count can not be a negative value.")

    def validate_event_nights_count(self, event_nights_count):
        if event_nights_count.data and event_nights_count.data < 0:
            raise ValidationError(
                "Event nights count can not be a negative value.")

flaskr/profiles/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from flaskr import bcrypt
from flaskr.models import User
from wtforms import (DateField, PasswordField, StringField, SubmitField,
                     TextAreaField)
from wtforms.validators import (URL, DataRequired, EqualTo, Length, Optional,
                                ValidationError)


class ProfileInfoForm(FlaskForm):
    bio = TextAreaField("Bio", validators=[Length(max=500)],  render_kw={
                        "placeholder": "Write your bio here..."})
    first_name = StringField("First Name", validators=[
        DataRequired(), Length(max=15, min=2)
    ], render_kw={"placeholder": "ex. Alen"})
    last_name = StringField("Last Name", validators=[
        DataRequired(), Length(max=15, min=2)
    ], render_kw={"placeholder": "ex. Walker"})
    dob = DateField("Date of Birth", validators=[
        DataRequired()
    ])
    nid = StringField("National Identity Card", validators=[
        Length(max=11)
    ], render_kw={"placeholder": "ex. 1234567890"})
    save = SubmitField("Update")


class VerifyEmailForm(FlaskForm):
    token = StringField("Verification Token", validators=[
        DataRequired(), Length(max=6)
    ], render_kw={"placeholder": "Enter your verification token here..."})
    save = SubmitField("Update")


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField("Old Password", validators=[
        DataRequired(), Length(min=6)
    ], render_kw={"placeholder": "Type your old password"})

    new_password = PasswordField("New Password", validators=[
        DataRequired(), Length(min=6)
    ], render_kw={"placeholder": "Type a new password"})

    c_password = PasswordField("Confirm Password", validators=[
        DataRequired(), Length(min=6), EqualTo(
            "new_password", "Confirm password did not matched")
    ], render_kw={"placeholder": "Retype the password"})

    save = SubmitField("Update")

    def validate_old_password(self, old_password):
        user = User.query.get(current_user.id)
        if not bcrypt.check_password_hash(user.password, old_password.data):
            raise ValidationError("Password did not matched.")


class ChangePhoto(FlaskForm):
    cover_photo = FileField("Cover Photo", validators=[
                            FileAllowed(["jpg", "jpeg", "png"])])
    profile_photo = FileField("Profile Photo", validators=[
                              FileAllowed(["jpg", "jpeg", "png"])])
    save = SubmitField("Update")


class ChangeConnections(FlaskForm):
    facebook = StringField("Facebook", validators=[Optional(), URL()], render_kw={
                           "placeholder": "Facebook profile link"})
    twitter = StringField("Twitter", validators=[Optional(), URL()], render_kw={
                          "placeholder": "Twitter profile link"})
    github = StringField("Github", validators=[Optional(), URL()], render_kw={
                         "placeholder": "Github profile link"})
    linkedin = StringField("Linkedin", validators=[Optional(), URL()], render_kw={
                           "placeholder": "Linkedin profile link"})
    website = StringField("Website", validators=[Optional(), URL()], render_kw={
                          "placeholder": "Website link"})
    save = SubmitField("Update")

flaskr/profiles/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flaskr import bcrypt, db
from flaskr.admins.forms import BanUserForm
from flaskr.decorators import is_general, is_unbanned, is_verified
from flaskr.models import (Complain, Event, Notification, Profile,
                           PromotionPending, Review, Role, SocialConnection,
                           User)
from flaskr.notifications.utils import NotificationMessage
from flaskr.profiles.forms import *
from flaskr.profiles.utils import remove_photo, save_photos

profiles = Blueprint("profiles", __name__, url_prefix="/profiles")


@profiles.route("/<int:id>")
@login_required
@is_unbanned
def view_profile(id: int):
    ban_user_form = BanUserForm()
    user = User.query.get(id)
    if not user:
        return render_template("mains/errors.html", status=404, message="User not found!")
    hosted_events = user.profile.hosted_events
    joined_events = user.profile.get_joined_events()
    return render_template("profiles/view-profile.html", user=user,
                           len=len, ban_form=ban_user_form,
                           hosted_events=hosted_events,
                           joined_events=joined_events)


@profiles.route("/settings/change-info", methods=["GET", "POST"])
@login_required
@is_unbanned
def change_profile_info():
    form = ProfileInfoForm()
    if form.validate_on_submit():
        current_user.profile.bio = form.bio.data
        current_user.profile.first_name = form.first_name.data
        current_user.profile.last_name = form.last_name.data
        current_user.profile.date_of_birth = form.dob.data
        current_user.profile.nid_number = form.nid.data
        db.session.commit()
        flash("Profile information updated successfully.", "success")
        return redirect(url_for("profiles.change_profile_info"))
    elif request.method == "GET":
        form.bio.data = current_user.profile.bio
        form.first_name.data = current_user.profile.first_name
        form.last_name.data = current_user.profile.last_name
        form.dob.data = current_user.profile.date_of_birth
        form.nid.data = current_user.profile.nid_number
    return render_template("profiles/edit-profile-info.html", active="edit-profile-info", form=form)


@profiles.route("/settings/change-photos", methods=["GET", "POST"])
@login_required
@is_unbanned
def change_photos():
    form = ChangePhoto()
    if form.validate_on_submit():
        if form.profile_photo.data:
            # deleting
            file_path = current_user.profile.profile_photo
            if not ("/images/default/ProfilePhotos/default.png" in file_path):
                remove_photo(file_path)
            # saving
            photo_file = save_photos(
                form.profile_photo.data, current_user.id, "profile", 250, 250)
            current_user.profile.profile_photo = "/images/uploads/profile/" + photo_file
            db.session.commit()
        if form.cover_photo.data:
            # deleting
            file_path = current_user.profile.cover_photo
            if not ("/images/default/CoverPhotos/default.png" in file_path):
                remove_photo(file_path)
            # saving
            photo_file = save_photos(
                form.cover_photo.data, current_user.id, "cover", 1040, 260)
            current_user.profile.cover_photo = "/images/uploads/cover/" + photo_file
            db.session.commit()
    return render_template("profiles/change-photos.html", active="change-photos", form=form)


@profiles.route("/settings/verify-email", methods=["GET", "POST"])
@login_required
@is_unbanned
def verify_email():
    form = VerifyEmailForm()
    if form.validate_on_submit():
        if not bcrypt.check_password_hash(current_user.verified_code, form.token.data):
            flash("Token did not matched!", "danger")
        else:
            current_user.verified_code = None
            current_user.is_verified = True
            db.session.commit()
            flash("Email verified successfully.", "success")
        return redirect(url_for("profiles.verify_email"))
    return render_template("profiles/verify-email.html", active="verify-email", form=form)


@profiles.route("/settings/change-password", methods=["GET", "POST"])
@login_required
@is_unbanned
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.new_password.data).decode("utf-8")
        current_user.password = hashed_password
        db.session.commit()
        flash("Password changed successfully.", "success")
        return redirect(url_for("profiles.change_password"))
    return render_template("profiles/change-password.html", active="change-password", form=form)


@profiles.route("/settings/remove-cover-photo")
@login_required
@is_unbanned
def remove_cover_photo():
    if not ("/images/default/CoverPhotos/default.png" in current_user.profile.cover_photo):
        remove_photo(current_user.profile.cover_photo)
        current_user.profile.cover_photo = "/images/default/CoverPhotos/default.png"
        db.session.commit()
        flash("Cover photo removed.", "success")
    else:
        flash("Cannot remove default cover photo.", "danger")
    return redirect(url_for("profiles.change_photos"))


@profiles.route("/settings/remove-profile-photo")
@login_required
@is_unbanned
def remove_profile_photo():
    if not ("/images/default/ProfilePhotos/default.png" in current_user.profile.profile_photo):
        remove_photo(current_user.profile.profile_photo)
        current_user.profile.profile_photo = "/images/default/ProfilePhotos/default.png"
        db.session.commit()
        flash("Profile photo removed.", "success")
    else:
        flash("Cannot remove default profile photo.", "danger")
    return redirect(url_for("profiles.change_photos"))


@profiles.route("/settings/connections", methods=["GET", "POST"])
@login_required
@is_unbanned
def change_connections():
    form = ChangeConnections()
    if form.validate_on_submit():
        if current_user.profile.social_links == None:
            social = SocialConnection(form.facebook.data, form.twitter.data, form.github.data,
                                      form.linkedin.data, form.website.data, current_user.profile.id)
            db.session.add(social)
        else:
            current_user.profile.social_links.facebook = form.facebook.data
            current_user.profile.social_links.twitter = form.twitter.data
            current_user.profile.social_links.github = form.github.data
            current_user.profile.social_links.linkedin = form.linkedin.data
            current_user.profile.social_links.website = form.website.data
        db.session.commit()
        flash("Connection information updated successfully.", "success")
        return redirect(url_for("profiles.change_connections"))
    elif request.method == "GET":
        form.facebook.data = current_user.profile.social_links.facebook if current_user.profile.social_links else None
        form.twitter.data = current_user.profile.social_links.twitter if current_user.profile.social_links else None
        form.github.data = current_user.profile.social_links.github if current_user.profile.social_links else None
        form.linkedin.data = current_user.profile.social_links.linkedin if current_user.profile.social_links else None
        form.website.data = current_user.profile.social_links.website if current_user.profile.social_links else None
    return render_template("profiles/change-connections.html", active="change-connections", form=form)


@profiles.route("/request_for_host")
@login_required
@is_unbanned
@is_general
def req_for_host():
    if current_user.profile.nid_number == None \
            or current_user.profile.nid_number == "":
        flash("Please add NID number in profile.", "danger")
        return redirect(url_for("mains.homepage"))
    is_pending = PromotionPending.query.filter_by(
        profile_id=current_user.profile.id).first()
    if is_pending:
        flash("Already requested for being host. Please wait for respose.", "danger")
        return redirect(url_for("mains.homepage"))
    # All ok
    new_pending_req = PromotionPending(current_user.profile.id)
    db.session.add(new_pending_req)
    # push notification
    users = User.query.filter_by(role=Role.ADMIN).all()
    for u in users:
        notification = Notification(
            NotificationMessage.want_promotion(
                current_user.profile.get_fullname()),
            url_for("admins.pending_request"),
            u.profile.id
        )
        db.session.add(notification)
    db.session.commit()
    flash("A request has been sent. Wait for the response from admins.", "success")
    return redirect(url_for("mains.homepage"))


@profiles.route("/complains")
@login_required
@is_unbanned
@is_verified
def view_complains():
    complains = None
    active = None
    if request.args.get("complains_by") == "self":
        complains = Profile.query.get(current_user.profile.id).complains
        active = "self"
    else:
        complains = Complain.query \
            .filter_by(complain_for=current_user.profile.id).all()
    return render_template("profiles/complains.html", len=len, complains=complains, active=active)


@profiles.route("/bookmark-profile/<int:id>")
@login_required
@is_unbanned
def bookmark_profile(id: int):
    list_of_bookmark = []
    bookmarks = current_user.profile.profile_bookmarks
    if bookmarks and id in bookmarks:
        flash("Profile already bookmarked.", "danger")
    else:
        if not bookmarks:
            list_of_bookmark.append(id)
        else:
            for i in range(len(bookmarks)):
                list_of_bookmark.append(bookmarks[i])
            list_of_bookmark.append(id)
        current_user.profile.profile_bookmarks = list_of_bookmark
        db.session.commit()

flaskr/templates/profiles/bookmarks.html
{% extends "layout.html" %}

{% block title %} Bookmarks {% endblock %}

{% block add_styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/profiles/bookmarks.css') }}">
{% endblock %}

{% block content %}
<div class="container mt-1">
    <div class="row mb-3">
        <div class="d-flex justify-content-center">
            <a href="{{ url_for('profiles.bookmarks') }}"
                class="btn btn-sm query-btn mx-1 {{ 'query-btn-active' if active == None or active == 'profile'}}">Profiles</a>
            <a href="{{ url_for('profiles.bookmarks', filter='event') }}"
                class="btn btn-sm query-btn mx-1 {{ 'query-btn-active' if active == 'event' }}">Events</a>
        </div>
    </div>

    {% if active == None or active == "profile" %}
    <div class="row">
        {% if bookmarks == None or len(bookmarks) == 0 %}
        <div class="col-md-8 offset-md-2 text-center fw-bold">
            <p class="empty-status">No bookmarked profile available</p>
        </div>
        {% else %}
        {% for bookmark in bookmarks %}
        <div class="col-md-8 offset-md-2 col-sm-12">
            <div class="card card-body shadow-card mb-2">
                <div class="d-flex flex-row">
                    <div class="d-flex flex-row align-self-center flex-grow-1">
                        <img src="{{ url_for('static', filename=bookmark.profile_photo) }}" alt=""
                            class="card-img align-self-center">
                        <a href="{{ url_for('profiles.view_profile', id=bookmark.id) }}"
                            class="d-flex flex-column align-self-center card-link-custom ms-3">
                            <h2 class="card-title-custom my-0">{{ bookmark.get_fullname() }}</h2>
                            <p class="card-body-custom my-0 text-muted">{{ bookmark.user.email }}</p>
                            <p class="card-body-custom my-0"><i class="fas fa-external-link-alt"></i></p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% else %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% if bookmarks == None or len(bookmarks) == 0 %}
        <div class="col-md-8 offset-md-2 text-center fw-bold">
            <p class="empty-status">No bookmarked event available</p>
        </div>
        {% else %}
        {% for bookmark in bookmarks %}
        <div class="col">
            <div class="card shadow-card event-card h-100">
                <img src="{{ url_for('static', filename=bookmark.cover_photo) }}"
                    class="card-img-top event-card-img" alt="Cover photo of the event">
                <div class="card-body">
                    <h5 class="card-title fw-bold">{{ bookmark.title }}</h5>
                    {% if len(bookmark.description) > 100 %}
                    <p class="card-text">{{ bookmark.description[:100] + "..."}}</p>
                    {% else %}
                    <p class="card-text">{{ bookmark.description }}</p>
                    {% endif %}
                    <a href="{{ url_for('events.view_event', id=bookmark.id) }}"
                        class="btn btn-dark w-100 btn-sm">Explore the event</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>        
    {% endif %}
</div>
{% endblock %}

flaskr/templates/profiles/change-password.html
{% extends "profiles/account-settings-layout.html" %}

{% block title %} Change password {% endblock %}

{% block settings %}
<h2 class="settings-header">Change Password</h2>
<div class="card card-body shadow-card p-4">
    <form method="POST">
        {{ form.hidden_tag() }}
        <div>
            {{ form.old_password.label(class="form-label mb-0") }}
            {% if form.old_password.errors %}
            {{ form.old_password(class="form-control input-box is-invalid")}}
            <div class="invalid-feedback">
                {% for error in form.old_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.old_password(class="form-control input-box", id="old_password") }}
            {% endif %}
        </div>
        <div class="mt-2">
            {{ form.new_password.label(class="form-label mb-0") }}
            {% if form.new_password.errors %}
            {{ form.new_password(class="form-control input-box is-invalid")}}
            <div class="invalid-feedback">
                {% for error in form.new_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.new_password(class="form-control input-box", id="new_password") }}
            {% endif %}
        </div>
        <div class="mt-2">
            {{ form.c_password.label(class="form-label mb-0") }}
    
            {% if form.c_password.errors %}
            {{ form.c_password(class="form-control input-box is-invalid")}}
            <div class="invalid-feedback">
                {% for error in form.c_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.c_password(class="form-control input-box", id="c_password") }}
            {% endif %}
        </div>
        <div class="mt-2">
            {{form.save(class="btn btn-dark btn-update")}}
        </div>
    </form>
</div>
{% endblock %}

flaskr/templates/profiles/change-photos.html
{% extends "profiles/account-settings-layout.html" %}

{% block title %} Change photos {% endblock %}

{% block settings %}
<h2 class="settings-header">Change Photo</h2>
<div class="card card-body shadow-card p-4">
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div>
            {{ form.cover_photo.label(class="form-label mb-0") }} <br>
            <img src="{{url_for('static', filename=current_user.profile.cover_photo)}}" alt="Cover Photo"
                class="cover-photo">
            <div class="mt-2">
                {% if form.cover_photo.errors %}
                <div class="d-flex">
                    {{ form.cover_photo(class="form-control is-invalid", id="cover_photo")}}
                    <button type="button" class="btn btn-danger ms-2" data-bs-toggle="modal"
                        data-bs-target="#delete-cover-modal">Delete</button>
                </div>
                <div class="invalid-feedback">
                    {% for error in form.cover_photo.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                <div class="d-flex">
                    {{ form.cover_photo(class="form-control", id="cover_photo") }}
                    <button type="button" class="btn btn-danger ms-2" data-bs-toggle="modal"
                        data-bs-target="#delete-cover-modal">Delete</button>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="mt-4">
            {{ form.profile_photo.label(class="form-label mb-0") }} <br>
            <div class="text-center">
                <img src="{{url_for('static', filename=current_user.profile.profile_photo)}}" alt="Profile Photo"
                    class="rounded-circle profile-photo">
            </div>
            <div class="mt-2">
                {% if form.profile_photo.errors %}
                <div class="d-flex">
                    {{ form.profile_photo(class="form-control is-invalid", id="profile_photo")}}
                    <button type="button" class="btn btn-danger ms-2" data-bs-toggle="modal"
                        data-bs-target="#delete-profile-modal">
                        Delete
                    </button>
                    <div class="invalid-feedback">
                        {% for error in form.profile_photo.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    <div class="d-flex">
                        {{ form.profile_photo(class="form-control", id="profile_photo") }}
                        <button type="button" class="btn btn-danger ms-2" data-bs-toggle="modal"
                            data-bs-target="#delete-profile-modal">Delete</button>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="mt-2">
                {{form.save(class="btn btn-dark btn-update")}}
            </div>
        </div>
    </form>
</div>
<!-- Modal Cover Photo -->
<div class="modal fade" id="delete-cover-modal" tabindex="-1" aria-labelledby="delete-cover-modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content modal-custom">
            <div class="modal-header modal-header-custom">
                <h5 class="modal-title text-danger" id="delete-cover-modal">Delete Cover Photo</h5>
                <button type="button" class="btn clr-white" data-bs-dismiss="modal" aria-label="Close"><i
                        class="bi bi-x-lg"></i></button>
            </div>
            <div class="modal-body modal-body-custom">
                Are you sure, You want to delete the current cover photo? It will set it to default cover photo.
                <br>
                <small class="text-muted">You will not be able to access the current photo after deleting this
                    photo.</small>
            </div>
            <div class="modal-footer modal-footer-custom">
                <button type="button" class="btn btn-sm btn-dark" data-bs-dismiss="modal">Close</button>
                <a href="{{ url_for('profiles.remove_cover_photo') }}" type="button"
                    class="btn btn-sm btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
<!-- Modal Profile Photo -->
<div class="modal fade" id="delete-profile-modal" tabindex="-1" aria-labelledby="delete-profile-modal"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content modal-custom">
            <div class="modal-header modal-header-custom">
                <h5 class="modal-title text-danger" id="delete-profile-modal">Delete Profile Photo</h5>
                <button type="button" class="btn clr-white" data-bs-dismiss="modal" aria-label="Close"><i
                        class="bi bi-x-lg"></i></button>
            </div>
            <div class="modal-body modal-body-custom">
                Are you sure, You want to delete the current profile photo? It will set it to default profile photo.
                <br>
                <small class="text-muted">You will not be able to access the current photo after deleting this
                    photo.</small>
            </div>
            <div class="modal-footer modal-footer-custom">
                <button type="button" class="btn btn-sm btn-dark" data-bs-dismiss="modal">Close</button>
                <a href="{{ url_for('profiles.remove_profile_photo') }}" type="button"
                    class="btn btn-sm btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flaskr/templates/profiles/complains.html
{% extends "layout.html" %}

{% block title %} Complains {% endblock %}

{% block add_styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/profiles/complains.css') }}">
{% endblock %}

{% block content %}
<div class="container mt-1">
    <div class="row mb-3">
        <div class="d-flex justify-content-center">
            <a href="{{ url_for('profiles.view_complains') }}"
                class="btn btn-sm query-btn mx-1 {{ 'query-btn-active' if active == None }}">
                Peoples Complains
            </a>
            <a href="{{ url_for('profiles.view_complains', complains_by='self') }}"
                class="btn btn-sm query-btn mx-1 {{ 'query-btn-active' if active == 'self' }}">
                My complains
            </a>
        </div>
    </div>
    <div class="row">
        {% if complains == None or len(complains) == 0 %}
        <div class="col-md-8 offset-md-2 text-center fw-bold">
            <p class="empty-status">No complains available</p>
        </div>
        {% else %}
        {% for complain in complains %}
        <div class="col-md-8 offset-md-2 col-sm-12">
            <div class="card card-body shadow-card px-4 mb-3">
                <div class="d-flex">
                    <img src="{{ url_for('static', filename=complain.complained_by.profile_photo) }}"
                        class="card-img align-self-center" alt="Profile Photo">
                    <a href="{{ url_for('profiles.view_profile', id=complain.complained_by.id) }}"
                        class="d-flex flex-column align-self-center card-link-custom ms-3">
                        <h2 class="card-title-custom my-0">{{ complain.complained_by.get_fullname() }}</h2>
                        <div class="card-body-custom my-0 text-muted text-capitalize">
                            {{ complain.complained_by.user.role.value }}
                        </div>
                        <div class="card-body-custom my-0 text-muted">{{ complain.get_days_ago() }}</div>
                    </a>
                </div>
                <p class="mt-1">{{ complain.text }}</p>
                <div class="fw-bold text-danger my-2" style="font-size: 0.8rem;">
                    The reported profile
                </div>
                <div class="d-flex">
                    <img src="{{ url_for('static', filename=complain.get_complain_for().profile_photo) }}"
                        class="card-img align-self-center" alt="Profile Photo">
                    <a href="{{ url_for('profiles.view_profile', id=complain.get_complain_for().id) }}"
                        class="d-flex flex-column align-self-center card-link-custom ms-3">
                        <h2 class="card-title-custom my-0">
                            {{ complain.get_complain_for().get_fullname() }}
                        </h2>
                        <p class="card-body-custom my-0 text-muted text-capitalize">
                            {{ complain.get_complain_for().user.role.value }}
                        </p>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}